### ISSUE TITLE
API for svg rainbow gradient

### ISSUE THREAD

**Issue by alex-page** [dominikwilkowski/rainbow-gradient#1]
It would be awesome to enter in a URL and generate a rainbow gradient SVG.

Something like this:
https://harmonograph.now.sh/red

This might be a separate project.

**Comment by dominikwilkowski** [comment]
Heyyyyy :)

This is just me re-learning some math and while doing that enable me to do this:
![Screen Shot 2018-12-04 at 10 32 26 am](https://user-images.githubusercontent.com/1266923/65361847-70d0d100-dc48-11e9-9228-83850fa24aff.png)

Remember that? :) It's all for cfonts.

**Comment by alex-page** [comment]
Nice nice nice!
